### ISSUE TITLE
New Adobe icons

### ISSUE THREAD

**Issue by weareblahs** [icon11-community/Folder11#12]
Adobe released a new set of folder icons starting from mid-2020 / 2021 Adobe CC releases. Here's some of these where you can see it where you go to `C:\Program Files\Adobe`:
![image](https://user-images.githubusercontent.com/37889443/160550932-81152fb4-f2f2-411c-8652-a08c6fd5eb30.png)

Not sure if needed to vectorize it. I think its original file is ICO so Windows can use it for folders.

**Comment by JangOetama** [comment]
SVG is only a medium to make modifications easier, after that the results of the ICO will automatically come [here](https://github.com/icon11-community/Folder11-Ico)
