### ISSUE TITLE
Steam Store Folder 

### ISSUE THREAD

**Issue by Nun-kany** [icon11-community/Folder11#22]
Steam Store folder

**Comment by niiick777** [comment]
What would this look like? Just a regular folder but with the Steam logo on it?

**Comment by Nun-kany** [comment]
Yes, The same concept that used with the Epic games folder icon

**Comment by nouvist** [comment]
we already have [steam](https://github.com/icon11-community/Folder11/blob/main/svg/steam.svg) and [steam-1](https://github.com/icon11-community/Folder11/blob/main/svg/steam-1.svg)
