### ISSUE TITLE
Request Icons

### ISSUE THREAD

**Issue by xmha97** [icon11-community/Folder11#3]
## Simplenote
[![Simplenote](https://is3-ssl.mzstatic.com/image/thumb/Purple126/v4/5e/e5/39/5ee5390d-8449-dbf4-b939-b90f3e322803/AppIcon-0-1x_U007emarketing-0-7-0-85-220.png/64x0w.png)](https://is3-ssl.mzstatic.com/image/thumb/Purple126/v4/5e/e5/39/5ee5390d-8449-dbf4-b939-b90f3e322803/AppIcon-0-1x_U007emarketing-0-7-0-85-220.png/1024x0w.png)
[See Full Size](https://is3-ssl.mzstatic.com/image/thumb/Purple126/v4/5e/e5/39/5ee5390d-8449-dbf4-b939-b90f3e322803/AppIcon-0-1x_U007emarketing-0-7-0-85-220.png/1024x0w.png)

## pCloud
[![pCloud](https://is4-ssl.mzstatic.com/image/thumb/Purple126/v4/11/6c/43/116c439c-6c39-3911-a076-dae6f5c2a176/AppIcon-0-0-1x_U007emarketing-0-0-0-4-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/64x0w.png)](https://is4-ssl.mzstatic.com/image/thumb/Purple126/v4/11/6c/43/116c439c-6c39-3911-a076-dae6f5c2a176/AppIcon-0-0-1x_U007emarketing-0-0-0-4-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/1024x0w.png)
[See Full Size](https://is4-ssl.mzstatic.com/image/thumb/Purple126/v4/11/6c/43/116c439c-6c39-3911-a076-dae6f5c2a176/AppIcon-0-0-1x_U007emarketing-0-0-0-4-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/1024x0w.png)

## TickTick
[![TickTick](https://is1-ssl.mzstatic.com/image/thumb/Purple116/v4/f6/b4/5b/f6b45b00-dc11-79af-50c6-876b06d031a7/AppIcon-0-0-1x_U007emarketing-0-0-0-7-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/64x0w.png)](https://is1-ssl.mzstatic.com/image/thumb/Purple116/v4/f6/b4/5b/f6b45b00-dc11-79af-50c6-876b06d031a7/AppIcon-0-0-1x_U007emarketing-0-0-0-7-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/1024x0w.png)
[See Full Size](https://is1-ssl.mzstatic.com/image/thumb/Purple116/v4/f6/b4/5b/f6b45b00-dc11-79af-50c6-876b06d031a7/AppIcon-0-0-1x_U007emarketing-0-0-0-7-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/1024x0w.png)

## Anghami
[![Anghami](https://is4-ssl.mzstatic.com/image/thumb/Purple116/v4/09/f5/e9/09f5e914-b3a7-300a-6c1e-73d8ff0427ca/AppIcon-0-0-1x_U007emarketing-0-0-0-7-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/64x0w.png)](https://is4-ssl.mzstatic.com/image/thumb/Purple116/v4/09/f5/e9/09f5e914-b3a7-300a-6c1e-73d8ff0427ca/AppIcon-0-0-1x_U007emarketing-0-0-0-7-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/1024x0w.png)
[See Full Size](https://is4-ssl.mzstatic.com/image/thumb/Purple116/v4/09/f5/e9/09f5e914-b3a7-300a-6c1e-73d8ff0427ca/AppIcon-0-0-1x_U007emarketing-0-0-0-7-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/1024x0w.png)

# Apple Podcasts
[![Apple Podcasts](https://is1-ssl.mzstatic.com/image/thumb/Purple116/v4/ad/6e/87/ad6e875a-89c0-ba9f-3fbb-99d4078ca852/AppIcon-0-0-1x_U007emarketing-0-0-0-10-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/64x0w.png)](https://is1-ssl.mzstatic.com/image/thumb/Purple116/v4/ad/6e/87/ad6e875a-89c0-ba9f-3fbb-99d4078ca852/AppIcon-0-0-1x_U007emarketing-0-0-0-10-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/1024x0w.png)
[See Full Size](https://is1-ssl.mzstatic.com/image/thumb/Purple116/v4/ad/6e/87/ad6e875a-89c0-ba9f-3fbb-99d4078ca852/AppIcon-0-0-1x_U007emarketing-0-0-0-10-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/1024x0w.png)

**Comment by JangOetama** [comment]
done

**Comment by xmha97** [comment]
Thanks 🙏
