### ISSUE TITLE
Request Icon: PortableApps.com

### ISSUE THREAD

**Issue by xmha97** [icon11-community/Folder11#4]
https://portableapps.com/

![Icon](https://user-images.githubusercontent.com/23485114/154942392-518d40a7-e2cf-4463-a27a-064c8124667f.png)

![Folder](https://user-images.githubusercontent.com/23485114/154942401-03a2334e-bc12-4d78-9037-f69a0eb65663.png)

**Comment by JangOetama** [comment]
done
