### ISSUE TITLE
Request Icon: PortableApps.com Package

### ISSUE THREAD

**Issue by xmha97** [icon11-community/Folder11#6]
Hi
I need an icon for the PortableApps.com package folder.
![portableapps com_package](https://user-images.githubusercontent.com/23485114/155572935-85593da5-70b9-4b91-ba26-b3ebd132bc0f.svg)
I'm not a designer and this is the worst icon that can be made. 😂

PS: Official PortableApps.com package icon is:
![01](https://user-images.githubusercontent.com/23485114/155572958-bbad2958-c6b1-4554-b799-3061f7aee5d3.png)
The design of this icon is very old and I like a flat icon.
Thanks

**Comment by JangOetama** [comment]
done
