### ISSUE TITLE
.svg missing elements in adobe illustrator

### ISSUE THREAD

**Issue by maxpanda** [icon11-community/Folder11#65]
### Issue description

When I view the .svg templates of already made icons either in chrome or explorer/finder then the bottom of the foler and the top section of the folder are clearly visible, but as soon as I bring it into Adobe Illustrator those sections are missing.

They exist as elements/objects in the base template but do not exist in any of the .svg templates in Adobe Illustrator.

I raised this on the F11 forum thread ten days ago but have not heard back.

This may very well be some sort of thing that I have missed with how .svg files work but it would be nice to be able to create my own folders with all of the elements.

<img width="1295" alt="Screenshot 2024-04-10 at 1 04 59 PM" src="https://github.com/icon11-community/Folder11/assets/7445488/b8032f01-f886-4348-8337-b0cd6039a68e">
<img width="290" alt="Screenshot 2024-04-10 at 1 04 29 PM" src="https://github.com/icon11-community/Folder11/assets/7445488/2b998490-fa28-4689-bb0d-9fc2fe70274e">

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/icon11-community/Folder11/issues' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not already fixed

**Comment by nouvist** [comment]
SVGs that maintained by @JangOetama mostly created on Figma and exported to SVG. We use SVG as the final format not as the editing format. I'm not sure why this particular thing happens. Maybe try to import it on other vector graphic software and then reexport it to Illustrator?

**Comment by maxpanda** [comment]
Ahh this makes sense.

Today I ended up getting the extra elements from the base .SVG template and just building what I need around that.

Thanks so much for letting me know what was missing in the whole process though!
