### ISSUE TITLE
Google Contacts

### ISSUE THREAD

**Issue by xmha97** [icon11-community/Folder11#9]
# Google Contacts Logo
![Google Contacts Logo](https://upload.wikimedia.org/wikipedia/commons/b/b7/Google_Contacts_logo.png)

# SVG
https://upload.wikimedia.org/wikipedia/commons/9/93/Google_Contacts_icon.svg

# PNG
https://upload.wikimedia.org/wikipedia/commons/b/b7/Google_Contacts_logo.png

**Comment by JangOetama** [comment]
done
